WebApplication/Controllers/TravelsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
//
using System.Reflection;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;
using Entities;

namespace WebApplication.Controllers
{
    public class TravelsController : Controller
    {
        private readonly IConfiguration _configuration;
        public TravelsController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        // GET: TravelsController
        public async Task<IActionResult> Index()
        {
            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                HttpResponseMessage res = await client.GetAsync("api/Travels");
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    ViewData["list"] = JsonConvert.DeserializeObject<List<Travels>>(result);
                }
                else
                {
                    ViewData["list"] = new List<Travels>();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return View();
        }

        // GET: TravelsController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                HttpResponseMessage res = await client.GetAsync("api/Travels/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    ViewData["item"] = JsonConvert.DeserializeObject<Travels>(result);
                }
                else
                {
                    ViewData["item"] = new Travels();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return View();
        }

        // GET: TravelsController/Create
        public async Task<IActionResult> Create()
        {
            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                HttpResponseMessage res = await client.GetAsync("api/Flights");
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    ViewData["listFlights"] = JsonConvert.DeserializeObject<List<Flights>>(result);
                }
                else
                {
                    ViewData["listFlights"] = new List<Flights>();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return View();
        }

        // POST: TravelsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Travels collection)
        {
            try
            {
                string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    var item = JsonConvert.SerializeObject(collection);

                    //Actualizar cupos de vuelo
                    HttpResponseMessage resFlights = await client.PutAsync("api/Flights/PutCupos/" + collection.FlightsId + "/" + -collection.PurchasedSeats, null);
                    if (!resFlights.IsSuccessStatusCode)
                    {
                        ModelState.AddModelError(string.Empty, "Cupos de vuelo agotados.");
                    }

                    //Crear el boleto
                    var content = new StringContent(item, Encoding.UTF8, "application/json");
                    HttpResponseMessage resTravels = await client.PostAsync("api/Travels", content);
                    if (resTravels.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                        return View();
                    }
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: TravelsController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(url);
                HttpResponseMessage res = await client.GetAsync("api/Travels/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    ViewData["item"] = JsonConvert.DeserializeObject<Travels>(result);
                }
                else
                {
                    ViewData["item"] = new Travels();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }



                HttpResponseMessage resFlights = await client.GetAsync("api/Flights");
                if (resFlights.IsSuccessStatusCode)
                {
                    var result = resFlights.Content.ReadAsStringAsync().Result;
                    ViewData["listFlights"] = JsonConvert.DeserializeObject<List<Flights>>(result);
                }
                else
                {
                    ViewData["listFlights"] = new List<Flights>();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return View(ViewData["item"]);
        }

        // POST: TravelsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Travels collection)
        {
            try
            {
                string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);

                    //Get boleto
                    HttpResponseMessage resGetTravels = await client.GetAsync("api/Travels/" + id);
                    if (!resGetTravels.IsSuccessStatusCode) { return RedirectToAction(nameof(Index)); }

                    var result = resGetTravels.Content.ReadAsStringAsync().Result;
                    Travels travels = JsonConvert.DeserializeObject<Travels>(result);

                    int cupos = travels.PurchasedSeats - collection.PurchasedSeats;


                    //Actualizar cupos de vuelo
                    HttpResponseMessage resFlights = await client.PutAsync("api/Flights/PutCupos/" + travels.FlightsId + "/" + cupos, null);


                    var item = JsonConvert.SerializeObject(collection);
                    var content = new StringContent(item, Encoding.UTF8, "application/json");

                    HttpResponseMessage res = await client.PutAsync("api/Travels/" + id, content);
                    if (res.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                        return View();
                    }
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: TravelsController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);

                    //Get boleto
                    HttpResponseMessage resGetTravels = await client.GetAsync("api/Travels/" + id);
                    if (!resGetTravels.IsSuccessStatusCode) { return RedirectToAction(nameof(Index)); }

                    var result = resGetTravels.Content.ReadAsStringAsync().Result;
                    Travels travels = JsonConvert.DeserializeObject<Travels>(result);

                    //Actualizar cupos de vuelo
                    HttpResponseMessage resFlights = await client.PutAsync("api/Flights/PutCupos/" + travels.FlightsId + "/" + travels.PurchasedSeats, null);


                    HttpResponseMessage res = await client.DeleteAsync("api/Travels/" + id);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

WebApplication/Controllers/UsersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
//
using System.Reflection;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;
using Entities;

namespace WebApplication.Controllers
{
    public class UsersController : Controller
    {
        private readonly IConfiguration _configuration; 
        public UsersController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        // GET: UsersController
        public async Task<IActionResult> Index()
        {
            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var item = new HttpClient())
            {
                item.BaseAddress = new Uri(url);
                HttpResponseMessage res = await item.GetAsync("api/Users");
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    ViewData["list"] = JsonConvert.DeserializeObject<List<Users>>(result);
                }
                else
                {
                    ViewData["list"] = new List<Users>();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return View();
        }

        // GET: UsersController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var item = new HttpClient())
            {
                item.BaseAddress = new Uri(url);
                HttpResponseMessage res = await item.GetAsync("api/Users/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    ViewData["item"] = JsonConvert.DeserializeObject<Users>(result);
                }
                else
                {
                    ViewData["item"] = new Users();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return View();
        }

        // GET: UsersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Users collection)
        {
            try
            {
                string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    var item = JsonConvert.SerializeObject(collection);

                    var content = new StringContent(item, Encoding.UTF8, "application/json");
                    HttpResponseMessage res = await client.PostAsync("api/Users", content);
                    if (res.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                        return View();
                    }
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: UsersController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var item = new HttpClient())
            {
                item.BaseAddress = new Uri(url);
                HttpResponseMessage res = await item.GetAsync("api/Users/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    ViewData["item"] = JsonConvert.DeserializeObject<Users>(result);
                }
                else
                {
                    ViewData["item"] = new Users();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return View(ViewData["item"]);
        }

        // POST: UsersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Users collection)
        {
            try
            {
                string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    var item = JsonConvert.SerializeObject(collection);

                    var content = new StringContent(item, Encoding.UTF8, "application/json");
                    HttpResponseMessage res = await client.PutAsync("api/Users/" + id, content);
                    if (res.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                        return View();
                    }
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: UsersController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            //return RedirectToAction("Delete", "Users");
            try
            {
                string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
                using (var item = new HttpClient())
                {
                    item.BaseAddress = new Uri(url);
                    HttpResponseMessage res = await item.DeleteAsync("api/Users/" + id);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: UsersController/GetUsersByCedula/5
        public async Task<Users> GetUsersByCedula(int cedula)
        {
            Users user = null;

            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var item = new HttpClient())
            {
                item.BaseAddress = new Uri(url);
                HttpResponseMessage res = await item.GetAsync("api/Users/GetUsersByCedula/" + cedula);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    user = JsonConvert.DeserializeObject<Users>(result);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return user;
        }
    }
}

WebApplication/Views/Travels/Create.cshtml
@model Entities.Travels;
@{
    ViewData["Title"] = "Crear un Boleto";
    List<Entities.Flights> apiListFlights = (List<Entities.Flights>)ViewData["listFlights"];
}
<h3>@ViewData["Title"]</h3>
<br />
<br />
<form asp-controller="Travels" asp-action="Create" method="post" autocomplete="off">
    <div class="mb-3 row">
        <label for="Cedula" class="col-sm-2 col-form-label">Cedula</label>
        <div class="col-sm-10">
            <input type="text" class="form-control validate numeric" id="Cedula" requerido maxlength="9" onfocusout="GetUsersByCedula()">
        </div>
    </div>

    <div id="usersInformation">
        <div class="mb-3 row">
            <label for="" class="col-sm-2 col-form-label">Nombre</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="Nombre" value="">
            </div>
        </div>

        <div class="mb-3 row">
            <label for="" class="col-sm-2 col-form-label">Apellido</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="Apellido" value="">
            </div>
        </div>

        <div class="mb-3 row">
            <label for="" class="col-sm-2 col-form-label">Telefono</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="Telefono" value="">
            </div>
        </div>

        <input type="hidden" class="form-control" id="UsersId" name="UsersId" value="">
    </div>



    <div class="mb-3 row">
        <label for="FlightsId" class="col-sm-2 col-form-label">FlightsId</label>
        <div class="col-sm-10">
            <select class="form-control" id="FlightsId" name="FlightsId" requerido onchange="FunctionChangeFlights()">
                <option selected disabled>Open this select menu</option>
                @foreach (var item in apiListFlights)
                {
                    <option value="@item.Id">@item.Origen - @item.Destino</option>
                }
            </select>
        </div>
    </div>

    <div id="flightsInformation">
        <div class="mb-3 row">
            <label for="" class="col-sm-2 col-form-label">Precio</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="Precio" value="">
            </div>
        </div>

        <div class="mb-3 row">
            <label for="" class="col-sm-2 col-form-label">Cupos Disponibles</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="Cupos" value="">
            </div>
        </div>

        <div class="mb-3 row">
            <label for="Cedula" class="col-sm-2 col-form-label">Asientos</label>
            <div class="col-sm-10">
                <input type="text" class="form-control validate numeric" id="PurchasedSeats" name="PurchasedSeats" requerido maxlength="2" onfocusout="ValidarCantidad()">
            </div>
        </div>
    </div>



    <div class="alert alert-danger" role="alert" id="error">
        <ul>
            <li id="errorUser">La cedula del usuario es incorrecta o no se encuentra en el sistema.</li>
            <li id="errorFlights">Se requiere seleccionar un buelo para el boleto.</li>
            <li id="errorCupos">Este vuelo no posee cupos disponibles, por favor seleccione otro.</li>
        </ul>
    </div>

    <button class="btn btn-success" type="submit" id="submitBtn" onclick="validationFiels()">Crear</button>
</form>


@section scripts
{
    <script type="text/javascript">
        //Oculta la informacion del usuario
        $(document).ready(function () {
            HideAllError();

            $('#usersInformation').hide();
            $('#flightsInformation').hide();
        });

        function HideAllError() {
            $('#error').hide();
            $('#errorUser').hide();
            $('#errorFlights').hide();
            $('#errorCupos').hide();
        }

        //Setea el precio del boleto
        function FunctionChangeFlights() {
            HideAllError();

            let flightsId = $("#FlightsId").val();
            let precio = 0;
            let cupos = 0;

            @foreach (var item in apiListFlights)
            {
                <text>
                if (flightsId == '@item.Id')
                {
                    precio = '@item.Precio';
                    cupos = '@item.Cupos';
                }
                </text>
            }
            $("#Precio").val(precio);
            $("#Cupos").val(cupos);

            $('#flightsInformation').show();

            if (cupos == 0) {
                $('#error').show();
                $('#errorCupos').show();

                $("#submitBtn").prop('disabled', true);
            } else {
                $("#submitBtn").prop('disabled', false);
                $('#error').hide();
                $('#errorCupos').hide();
            }
        }

        //busca la informacion del usuario
        function GetUsersByCedula() {
            HideAllError();
            let x = $("#Cedula").val();

            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetUsersByCedula", "Users")',
                global: false,
                data: {
                    cedula: x
                },
                cache: false,
                success: function (data) {
                    if (data != null) {
                        $('#usersInformation').show();

                        $("#UsersId").val(data['id']);
                        $("#Nombre").val(data['nombre']);
                        $("#Apellido").val(data['apellido']);
                        $("#Telefono").val(data['telefono']);

                        $("#submitBtn").prop('disabled', false);
                    } else {
                        $('#usersInformation').hide();

                        $("#submitBtn").prop('disabled', true);

                        $('#error').show();
                        $('#errorUser').show();
                    }
                }
            });
        }

        //Validar que la cantidad no pase el maximo de cupos del vuelo
        function ValidarCantidad() {
            let purchasedSeats = $("#PurchasedSeats").val();
            let cupos = $("#Cupos").val();

            if (purchasedSeats > cupos) {
                $("#PurchasedSeats").val(cupos);
            }
        }

        //evitar el submit y mostrar el error para cedula errada para el boleto o no posee vuelo
        $("form").submit(function (e) {
            HideAllError();

            let x = $("#Cedula").val();
            let y = $("#FlightsId").val();

            if (x == "" || y == null) {
                if (x == "") {
                    $('#errorUser').show();
                }


                if (y == null) {
                    $('#errorFlights').show();
                }

                $('#error').show();
                event.preventDefault();
            }
        });
    </script>
}

WebApplication/Views/Travels/Details.cshtml
@{
    ViewData["_Title"] = "Boletos";
    Entities.Travels apiItem = (Entities.Travels)ViewData["item"];
}

<div class="card">
    <div class="card-header">
        Datos del @ViewData["_Title"]
    </div>
    <div class="card-body">
        <blockquote class="blockquote mb-0">
            <p>Nombre completo del Usuario: @apiItem.Users.Nombre @apiItem.Users.Apellido</p>
            <p>Informacion de contacto (Telf): @apiItem.Users.Telefono.</p>

            <p>Origen - Destino: @apiItem.Flights.Origen - @apiItem.Flights.Destino.</p>
            <p>Cantidad de Asientos Comprados: @apiItem.PurchasedSeats.</p>
            <p id="text"></p>
        </blockquote>
    </div>
    <input type="hidden" id="PurchasedSeats" name="PurchasedSeats" value="@apiItem.PurchasedSeats">
    <input type="hidden" id="Precio" name="Precio" value="@apiItem.Flights.Precio">
</div>
<br />
<a asp-controller="Travels" asp-action="Edit" asp-route-id="@apiItem.Id" class="btn btn-success">Actualizar</a>
<button onclick="FunctionDelete(@apiItem.Id)" type="button" class="btn btn-danger" id="">Borrar</button>


@section scripts
{
    <script type="text/javascript">
        //Oculta la informacion del usuario
        $(document).ready(function () {
            let purchasedSeats = $("#PurchasedSeats").val();
            let precio = $("#Precio").val();
            console.log(purchasedSeats);
            console.log(precio);
            console.log(purchasedSeats * precio);

            $("#text").text("Costo: " + (purchasedSeats * precio) + ".");
        });

        function FunctionDelete(id) {
        let opcion = confirm("¿Seguro que desea eliminar?");
        if (opcion == true) {
            location.href = '@Url.Action("Delete", "Travels")?id=' + id;
        }
    }
    </script>
}

WebApplication/Views/Travels/Edit.cshtml
@model Entities.Travels;
@{
    ViewData["Title"] = "Crear un Boleto";
    List<Entities.Flights> apiListFlights = (List<Entities.Flights>)ViewData["listFlights"];
}
<h3>@ViewData["Title"]</h3>
<br />
<br />
<form asp-controller="Travels" asp-action="Create" method="post" autocomplete="off">
    <div class="mb-3 row">
        <label for="" class="col-sm-2 col-form-label">Cedula</label>
        <div class="col-sm-10">
            <input type="text" readonly disabled class="form-control validate numeric" id="Cedula" value="@Html.DisplayFor(m => m.Users.Cedula)">
        </div>
    </div>

    <div id="usersInformation">
        <div class="mb-3 row">
            <label for="" class="col-sm-2 col-form-label">Nombre</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="Nombre" value="@Html.DisplayFor(m => m.Users.Nombre)">
            </div>
        </div>

        <div class="mb-3 row">
            <label for="" class="col-sm-2 col-form-label">Apellido</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="Apellido" value="@Html.DisplayFor(m => m.Users.Apellido)">
            </div>
        </div>

        <div class="mb-3 row">
            <label for="" class="col-sm-2 col-form-label">Telefono</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="Telefono" value="@Html.DisplayFor(m => m.Users.Telefono)">
            </div>
        </div>

        <input type="hidden" class="form-control" id="UsersId" name="UsersId" value="@Html.DisplayFor(m => m.UsersId)">
    </div>



    <div class="mb-3 row">
        <label for="FlightsId" class="col-sm-2 col-form-label">FlightsId</label>
        <div class="col-sm-10">
            <input type="hidden" class="form-control" id="FlightsId" name="FlightsId" value="@Html.DisplayFor(m => m.FlightsId)">
            <input type="text" readonly class="form-control-plaintext" value="@Html.DisplayFor(m => m.Flights.Origen) - @Html.DisplayFor(m => m.Flights.Destino)">
            @*<select disabled requerido class="form-control" id="FlightsId" name="FlightsId" value="@Html.DisplayFor(m => m.FlightsId)">
            <option disabled>Open this select menu</option>
            @foreach (var item in apiListFlights)
            {
                if (item.Id == Model.FlightsId)
                {
                    <option selected value="@item.Id">@item.Origen - @item.Destino</option>
                }
                else
                {
                    <option value="@item.Id">@item.Origen - @item.Destino</option>
                }

            }
        </select>*@
        </div>
    </div>

    <div id="flightsInformation">
        <div class="mb-3 row">
            <label for="" class="col-sm-2 col-form-label">Precio</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="Precio" value="@Html.DisplayFor(m => m.Flights.Precio)">
            </div>
        </div>

        <div class="mb-3 row">
            <label for="" class="col-sm-2 col-form-label">Cupos Disponibles</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="Cupos" value="@Html.DisplayFor(m => m.Flights.Cupos)">
            </div>
        </div>

        <div class="mb-3 row">
            <label for="Cedula" class="col-sm-2 col-form-label">Asientos</label>
            <div class="col-sm-10">
                <input type="text" class="form-control validate numeric" id="PurchasedSeats" name="PurchasedSeats" requerido maxlength="2" value="@Html.DisplayFor(m => m.PurchasedSeats)">
            </div>
        </div>
    </div>

    <input type="hidden" class="form-control" id="id" name="id" value="@Html.DisplayFor(m => m.Id)">
    <button class="btn btn-success" type="submit" id="submitBtn" onclick="validationFiels()" asp-route-id="@Html.DisplayFor(m => m.Id)">Actualizar</button>
</form>


@section scripts
{
    <script type="text/javascript">
        let initialPurchasedSeats;
        //Oculta la informacion del usuario
        $(document).ready(function () {
            initialPurchasedSeats = $("#PurchasedSeats").val();
        });

        $("form").submit(function (e) {
            let purchasedSeats = $("#PurchasedSeats").val();
            if (initialPurchasedSeats == purchasedSeats) {
                event.preventDefault();
            }
        });
    </script>
}