WebApplication/Controllers/FlightsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
//
using System.Reflection;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;
using Entities;

namespace WebApplication.Controllers
{
    public class FlightsController : Controller
    {
        private readonly IConfiguration _configuration;
        public FlightsController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        // GET: FlightsController
        public async Task<IActionResult> Index()
        {
            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var item = new HttpClient())
            {
                item.BaseAddress = new Uri(url);
                HttpResponseMessage res = await item.GetAsync("api/Flights");
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    ViewData["list"] = JsonConvert.DeserializeObject<List<Flights>>(result);
                }
                else
                {
                    ViewData["list"] = new List<Flights>();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return View();
        }

        // GET: FlightsController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var item = new HttpClient())
            {
                item.BaseAddress = new Uri(url);
                HttpResponseMessage res = await item.GetAsync("api/Flights/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    ViewData["item"] = JsonConvert.DeserializeObject<Flights>(result);
                }
                else
                {
                    ViewData["item"] = new Flights();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return View();
        }

        // GET: FlightsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FlightsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Flights collection)
        {
            try
            {
                string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    var item = JsonConvert.SerializeObject(collection);

                    var content = new StringContent(item, Encoding.UTF8, "application/json");
                    HttpResponseMessage res = await client.PostAsync("api/Flights", content);
                    if (res.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                        return View();
                    }
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightsController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var item = new HttpClient())
            {
                item.BaseAddress = new Uri(url);
                HttpResponseMessage res = await item.GetAsync("api/Flights/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    ViewData["item"] = JsonConvert.DeserializeObject<Flights>(result);
                }
                else
                {
                    ViewData["item"] = new Flights();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return View(ViewData["item"]);
        }

        // POST: FlightsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Flights collection)
        {
            try
            {
                string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    var item = JsonConvert.SerializeObject(collection);

                    var content = new StringContent(item, Encoding.UTF8, "application/json");
                    HttpResponseMessage res = await client.PutAsync("api/Flights/" + id, content);
                    if (res.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                        return View();
                    }
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightsController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
                using (var item = new HttpClient())
                {
                    item.BaseAddress = new Uri(url);
                    HttpResponseMessage res = await item.DeleteAsync("api/Flights/" + id);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

WebApplication/Controllers/UsersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
//
using System.Reflection;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;
using Entities;

namespace WebApplication.Controllers
{
    public class UsersController : Controller
    {
        private readonly IConfiguration _configuration; 
        public UsersController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        // GET: UsersController
        public async Task<IActionResult> Index()
        {
            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var item = new HttpClient())
            {
                item.BaseAddress = new Uri(url);
                HttpResponseMessage res = await item.GetAsync("api/Users");
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    ViewData["list"] = JsonConvert.DeserializeObject<List<Users>>(result);
                }
                else
                {
                    ViewData["list"] = new List<Users>();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return View();
        }

        // GET: UsersController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var item = new HttpClient())
            {
                item.BaseAddress = new Uri(url);
                HttpResponseMessage res = await item.GetAsync("api/Users/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    ViewData["item"] = JsonConvert.DeserializeObject<Users>(result);
                }
                else
                {
                    ViewData["item"] = new Users();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return View();
        }

        // GET: UsersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Users collection)
        {
            try
            {
                string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    var item = JsonConvert.SerializeObject(collection);

                    var content = new StringContent(item, Encoding.UTF8, "application/json");
                    HttpResponseMessage res = await client.PostAsync("api/Users", content);
                    if (res.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                        return View();
                    }
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: UsersController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var item = new HttpClient())
            {
                item.BaseAddress = new Uri(url);
                HttpResponseMessage res = await item.GetAsync("api/Users/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    ViewData["item"] = JsonConvert.DeserializeObject<Users>(result);
                }
                else
                {
                    ViewData["item"] = new Users();
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return View(ViewData["item"]);
        }

        // POST: UsersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Users collection)
        {
            try
            {
                string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(url);
                    var item = JsonConvert.SerializeObject(collection);

                    var content = new StringContent(item, Encoding.UTF8, "application/json");
                    HttpResponseMessage res = await client.PutAsync("api/Users/" + id, content);
                    if (res.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                        return View();
                    }
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: UsersController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            //return RedirectToAction("Delete", "Users");
            try
            {
                string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
                using (var item = new HttpClient())
                {
                    item.BaseAddress = new Uri(url);
                    HttpResponseMessage res = await item.DeleteAsync("api/Users/" + id);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: UsersController/GetUsersByCedula/5
        public async Task<Users> GetUsersByCedula(int cedula)
        {
            Users user = null;

            string url = _configuration.GetSection("UrlBase").GetSection("Ruta").Value;
            using (var item = new HttpClient())
            {
                item.BaseAddress = new Uri(url);
                HttpResponseMessage res = await item.GetAsync("api/Users/GetUsersByCedula/" + cedula);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    user = JsonConvert.DeserializeObject<Users>(result);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error en el servidor: " + this.GetType().Name + "/" + MethodBase.GetCurrentMethod().Name);
                }
            }
            return user;
        }
    }
}

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/fontawesome-free-5.15.3-web/css/all.min.css" >
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Usuarios
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Lista</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Create">Nuevo</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Vuelos
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Flights" asp-action="Index">Lista</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Flights" asp-action="Create">Nuevo</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Boletos
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Travels" asp-action="Index">Lista</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Travels" asp-action="Create">Nuevo</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script defer src="~/lib/fontawesome-free-5.15.3-web/js/all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>